[project]
name = "pyyne-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fuzzywuzzy>=0.18.0",
    "notebook>=7.4.2",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
]
